INSERT INTO USERS(ID,USER_NAME,CITY,STATE,POST_CODE,PEANUT_ALLERGY,EGG_ALLERGY,DAIRY_ALLERGY) VALUES (1,'BilboBaggins','London','Westminster','SE1',true,false,false);
INSERT INTO USERS(ID,USER_NAME,CITY,STATE,POST_CODE,PEANUT_ALLERGY,EGG_ALLERGY,DAIRY_ALLERGY) VALUES (2,'BigJock','Bristol','Clifton','BS8',false,true,false);
INSERT INTO USERS(ID,USER_NAME,CITY,STATE,POST_CODE,PEANUT_ALLERGY,EGG_ALLERGY,DAIRY_ALLERGY) VALUES (3,'NorthernSoul','Manchester','Hulme','M1',false,false,false);

